# Generated by Django 3.0.5 on 2021-06-20 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_auto_20210519_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_result',
            name='attempted_date',
            field=models.DateField(default=datetime.date(2021, 6, 20)),
        ),
        migrations.AlterField(
            model_name='quiz_result',
            name='attempted_time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 20, 7, 54, 28, 685515)),
        ),
    ]
